In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,StandardScaler
from sklearn.decomposition import PCA

In [2]:
DES_df = pd.read_csv('D:\\2020\\資料科學\\final-project\\DES\\diffSig_D.txt',sep='\t',engine='python')

In [3]:
DES_df.head()

,id,baseMean,baseMeanA,baseMeanB,foldChange,log2FoldChange,pval,padj
0,MMP11,17170.546772,248.439330,18894.801182,76.053986,6.248952,1.697352e-113,5.136697e-109
1,COL10A1,8580.135868,67.933818,9447.474760,139.068803,7.119655,1.711757e-98,2.590144e-94
2,CAV1,8624.914567,48164.922854,4596.040865,0.095423,-3.389519,2.270902e-89,2.290811e-85
3,GSN,37594.765020,150996.854034,26039.818168,0.172453,-2.535727,9.876324e-89,7.472180e-85
4,OXTR,2017.287314,13819.146545,814.753415,0.058958,-4.084161,3.633044e-80,2.198936e-76

In [4]:
DES_df.shape[0]

3618

In [5]:
edge_df = pd.read_csv('D:\\2020\\資料科學\\final-project\\edgeR\\diffSig.xls',sep='\t',engine='python')
edge_df.head()

      id     logFC    logCPM  PValue  FDR
0    CKM -8.314478  5.269065     0.0  0.0
1  ACTA1 -6.990036  6.347895     0.0  0.0
2  MYLPF -6.960771  2.428542     0.0  0.0
3   PYGM -6.946510  3.900152     0.0  0.0
4    SLN -6.461278  1.779354     0.0  0.0

In [6]:
edge_df.shape[0]

9064

In [7]:
edge=pd.DataFrame(edge_df['id'])
itersection=pd.merge(DES_df,edge,how='inner')
itersection.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3563 entries, 0 to 3562
Data columns (total 8 columns):
id                3563 non-null object
baseMean          3563 non-null float64
baseMeanA         3563 non-null float64
baseMeanB         3563 non-null float64
foldChange        3563 non-null float64
log2FoldChange    3563 non-null float64
pval              3563 non-null float64
padj              3563 non-null float64
dtypes: float64(7), object(1)
memory usage: 250.5+ KB

In [8]:
itersection.to_csv('D:\\2020\\資料科學\\final-project\\DES\\diffSig_D_filter.csv',index=False)

In [9]:
exp = pd.read_csv('D:\\2020\\資料科學\\final-project\\DES\\diffmRNAExp_D.csv',sep='\t',engine='python')

In [10]:
des_f = pd.DataFrame(itersection['id'])
exp_f=pd.merge(des_f,exp,how='inner')

In [11]:
exp_f.head(15)

,id,TCGA-BH-A1FH-11B-42R-A13Q-07,TCGA-A7-A13E-11A-61R-A12P-07,TCGA-BH-A0DK-11A-13R-A089-07,TCGA-BH-A18Q-11A-34R-A12D-07,TCGA-BH-A0BJ-11A-23R-A089-07,TCGA-BH-A1FD-11B-21R-A13Q-07,TCGA-BH-A1FN-11A-34R-A13Q-07,TCGA-AC-A2FM-11B-32R-A19W-07,TCGA-E9-A1NA-11A-33R-A144-07,...,TCGA-BH-A1FE-01A-11R-A13Q-07,TCGA-AN-A0XV-01A-11R-A109-07,TCGA-XX-A89A-01A-11R-A36F-07,TCGA-LL-A441-01A-11R-A24H-07,TCGA-E2-A15O-01A-11R-A115-07,TCGA-C8-A12P-01A-11R-A115-07,TCGA-BH-A1F0-01A-11R-A137-07,TCGA-OL-A66K-01A-11R-A29R-07,TCGA-BH-A0GY-01A-11R-A056-07,TCGA-AO-A12B-01A-11R-A10J-07
0,MMP11,283.354927,281.298283,282.684162,131.750821,270.574934,95.295040,535.179290,247.989614,148.209298,...,11637.867839,18224.001354,21724.088545,1094.046308,10679.254688,46796.039141,6210.886914,5379.573421,16263.017890,4206.826241
1,COL10A1,25.636874,51.639298,158.150328,23.819357,30.612493,47.647520,38.720982,52.573798,17.376263,...,7136.050713,11127.055523,12669.969587,854.768723,2480.614278,25712.418220,1162.072796,9348.317080,7797.658574,892.395169
2,CAV1,41731.434147,114718.060052,9453.875192,25014.047047,13529.734219,82249.149080,30257.681800,16398.065268,43533.670429,...,5042.275385,10126.832137,12197.759301,6531.124927,1567.201648,3028.164139,14169.611416,3172.273743,3312.585567,2058.793362
3,GSN,150941.820108,139587.817888,57750.846284,78848.027841,63343.172138,142900.976808,49061.558777,174826.726462,212137.589996,...,16055.613681,31883.409384,51885.161890,19493.195311,11102.851110,43643.106546,25410.398865,22313.716990,17739.117867,15239.847079
4,OXTR,7664.076111,5931.724657,20630.595751,8463.315427,12915.509368,7430.414169,14295.648337,16048.895891,6957.659942,...,317.602631,300.754455,443.225511,399.997168,342.661125,946.441799,447.250612,327.588809,241.902672,96.780885
5,CHRDL1,31963.785033,47302.956151,2224.036745,12348.103748,9250.897756,25067.793448,11365.991166,3814.080271,35837.008263,...,1608.030128,2642.342709,8135.060064,1658.366636,132.439576,35.969285,5424.860652,223.974458,431.969057,90.496412
6,COL11A1,28.335493,154.917895,77.165136,211.396797,399.937403,41.583290,154.883929,34.718546,227.935679,...,4483.134618,10698.265600,21158.885441,491.528051,2534.220773,51912.669862,2376.436086,6022.191724,8377.731307,677.466192
7,DST,56722.259075,39056.975573,66539.267679,127219.932241,65976.833999,42133.402487,37965.231595,31635.539141,51554.348785,...,26403.054023,11902.142717,7999.797783,17212.130381,5383.773869,10912.181687,9194.226503,4841.616079,10469.695739,7714.819082
8,SYNM,33725.982815,19067.131424,47910.381400,37323.444340,43277.177004,33165.272898,29353.270287,37364.099235,35547.744598,...,1427.877375,960.695658,1612.278086,10599.564589,2060.171180,834.037784,5410.953606,1852.499018,1146.569296,1605.054410
9,SCARA5,7778.767391,12125.722593,3884.997200,2083.449418,2120.161986,1587.095576,3364.576774,3003.650211,6102.134546,...,185.490612,577.448553,933.551281,575.851779,26.277694,7.868281,1742.274771,61.749967,78.988628,6.284473
10,ITIH5,10624.460440,50216.499717,3424.298417,7366.136277,8220.935506,16137.781876,4442.541261,6326.711045,31410.149851,...,953.475126,1457.370157,9486.475179,2577.999764,484.560670,128.140576,2691.291616,815.308890,819.507011,586.969780
11,LYVE1,20263.925182,15018.882225,561.548268,4984.200536,3719.911598,7815.059604,3852.046282,3260.567451,19831.426209,...,274.232524,421.915535,1422.669352,312.790578,38.890987,93.295332,2061.024274,77.449112,145.635282,21.367208
12,TNS1,40174.331360,151833.126224,14355.007353,43482.981293,21551.194773,92625.046306,17501.192505,16120.316900,133570.307913,...,10523.589701,9108.563483,25379.793238,7587.694023,4825.635657,6419.393244,11788.168794,6298.496663,7405.183831,3408.698167
13,EGR1,110262.847117,34739.658452,79424.317389,101315.636711,147451.489240,177752.971915,187901.172001,76089.165475,18198.057531,...,26936.839958,18572.876521,10878.952058,10651.456114,11803.939975,3421.578189,29189.777790,19745.336995,3086.727460,2824.242176
14,MME,14312.122413,25156.491834,12688.698820,12661.477169,14618.946455,17688.492073,11202.809884,8293.764667,13192.671790,...,3165.350592,1092.168320,3684.689468,1232.423706,388.909866,1370.204932,1045.253606,584.008165,2525.167686,55.303363

In [12]:
exp_f.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3563 entries, 0 to 3562
Columns: 1223 entries, id to TCGA-AO-A12B-01A-11R-A10J-07
dtypes: float64(1222), object(1)
memory usage: 33.3+ MB

In [13]:
transfer=exp_f.values
index1=list(exp_f.keys())
transfer=list(map(list, zip(*transfer)))
transfer = pd.DataFrame(transfer, index=index1)
transfer.head()

,0,1,2,3,4,5,6,7,8,9,...,3553,3554,3555,3556,3557,3558,3559,3560,3561,3562
id,MMP11,COL10A1,CAV1,GSN,OXTR,CHRDL1,COL11A1,DST,SYNM,SCARA5,...,ADAMTS19,RHPN1-AS1,CCND2-AS1,JPH3,HLA-DQB2,GRPR,BARX1-DT,PASK,DSCR8,GRAMD4P7
TCGA-BH-A1FH-11B-42R-A13Q-07,283.355,25.6369,41731.4,150942,7664.08,31963.8,28.3355,56722.3,33726,7778.77,...,35.082,82.3079,9.44516,18.8903,717.832,32.3834,0,360.266,0,1.34931
TCGA-A7-A13E-11A-61R-A12P-07,281.298,51.6393,114718,139588,5931.72,47303,154.918,39057,19067.1,12125.7,...,29.8964,91.0482,0,16.3071,554.443,332.938,0,243.248,0,6.79464
TCGA-BH-A0DK-11A-13R-A089-07,282.684,158.15,9453.88,57750.8,20630.6,2224.04,77.1651,66539.3,47910.4,3885,...,51.1888,139.814,3.82006,3.05604,407.982,640.241,0,560.02,4.58407,29.0324
TCGA-BH-A18Q-11A-34R-A12D-07,131.751,23.8194,25014,78848,8463.32,12348.1,211.397,127220,37323.4,2083.45,...,26.0524,88.5782,5.95484,28.2855,212.141,646.844,1.48871,685.551,0,11.1653

In [14]:
transfer.to_csv('D:\\2020\\資料科學\\final-project\\DES\\diffmRNAExp_f_t.csv',header=False)

In [18]:
transfer=pd.read_csv('D:\\2020\\資料科學\\final-project\\DES\\diffmRNAExp_f_t.csv',engine='python')

In [19]:
transfer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1222 entries, 0 to 1221
Columns: 3564 entries, id to GRAMD4P7
dtypes: float64(3563), object(1)
memory usage: 33.2+ MB

In [20]:
transfer=transfer.sort_values(by=['id'])

In [21]:
transfer.head()

,id,MMP11,COL10A1,CAV1,GSN,OXTR,CHRDL1,COL11A1,DST,SYNM,...,ADAMTS19,RHPN1-AS1,CCND2-AS1,JPH3,HLA-DQB2,GRPR,BARX1-DT,PASK,DSCR8,GRAMD4P7
693,TCGA-3C-AAAU-01A-11R-A41B-07,21873.126656,3520.656342,1012.464785,9876.390778,225.286667,236.771869,1597.326642,12505.618701,2793.554669,...,348.973464,329.536968,0.000000,83.046850,292.430928,1279.274877,0.000000,2623.927061,57.426013,2.650431
666,TCGA-3C-AALI-01A-11R-A41B-07,18143.286550,7426.918006,2303.185472,22327.786889,3922.256448,380.538689,15369.772361,11665.577409,1878.464389,...,12.827147,510.235396,2.850477,1550.659526,1621.921453,7.126193,1.425239,2259.003078,0.000000,0.000000
337,TCGA-3C-AALJ-01A-31R-A41B-07,27974.425254,7941.952116,3618.158269,25587.577390,177.592847,776.672717,8676.002550,6158.919933,596.711966,...,0.000000,644.070058,0.000000,54.461806,480.684639,9.471619,2.367905,2164.264828,0.000000,18.943237
893,TCGA-3C-AALK-01A-11R-A41B-07,16301.894223,14298.570862,4169.872416,33188.136433,938.003659,369.978241,19877.625110,11133.080555,3103.464543,...,23.939769,213.281575,1.088171,68.554792,1697.547226,221.986945,0.000000,1143.668035,7.617199,3.264514
1123,TCGA-4H-AAAK-01A-12R-A41B-07,63599.110508,36470.689263,4700.813746,27583.891056,133.558817,257.985407,51532.014317,7938.188148,2940.577030,...,157.530912,287.665144,1.141528,108.445193,763.682466,444.054528,0.000000,1076.461234,0.000000,10.273755

In [22]:
# transfer.iloc[0]=transfer.iloc[0].apply(lambda x: x[:12]
transfer['id']=transfer['id'].apply(lambda x: x[:12])
transfer.head()

,id,MMP11,COL10A1,CAV1,GSN,OXTR,CHRDL1,COL11A1,DST,SYNM,...,ADAMTS19,RHPN1-AS1,CCND2-AS1,JPH3,HLA-DQB2,GRPR,BARX1-DT,PASK,DSCR8,GRAMD4P7
693,TCGA-3C-AAAU,21873.126656,3520.656342,1012.464785,9876.390778,225.286667,236.771869,1597.326642,12505.618701,2793.554669,...,348.973464,329.536968,0.000000,83.046850,292.430928,1279.274877,0.000000,2623.927061,57.426013,2.650431
666,TCGA-3C-AALI,18143.286550,7426.918006,2303.185472,22327.786889,3922.256448,380.538689,15369.772361,11665.577409,1878.464389,...,12.827147,510.235396,2.850477,1550.659526,1621.921453,7.126193,1.425239,2259.003078,0.000000,0.000000
337,TCGA-3C-AALJ,27974.425254,7941.952116,3618.158269,25587.577390,177.592847,776.672717,8676.002550,6158.919933,596.711966,...,0.000000,644.070058,0.000000,54.461806,480.684639,9.471619,2.367905,2164.264828,0.000000,18.943237
893,TCGA-3C-AALK,16301.894223,14298.570862,4169.872416,33188.136433,938.003659,369.978241,19877.625110,11133.080555,3103.464543,...,23.939769,213.281575,1.088171,68.554792,1697.547226,221.986945,0.000000,1143.668035,7.617199,3.264514
1123,TCGA-4H-AAAK,63599.110508,36470.689263,4700.813746,27583.891056,133.558817,257.985407,51532.014317,7938.188148,2940.577030,...,157.530912,287.665144,1.141528,108.445193,763.682466,444.054528,0.000000,1076.461234,0.000000,10.273755

In [23]:
transfer=transfer.drop_duplicates('id','first')
transfer.shape

(1092, 3564)

In [24]:
filter10=transfer.iloc[:,0:11]
filter10.head()

,id,MMP11,COL10A1,CAV1,GSN,OXTR,CHRDL1,COL11A1,DST,SYNM,SCARA5
693,TCGA-3C-AAAU,21873.126656,3520.656342,1012.464785,9876.390778,225.286667,236.771869,1597.326642,12505.618701,2793.554669,26.504314
666,TCGA-3C-AALI,18143.286550,7426.918006,2303.185472,22327.786889,3922.256448,380.538689,15369.772361,11665.577409,1878.464389,59.860018
337,TCGA-3C-AALJ,27974.425254,7941.952116,3618.158269,25587.577390,177.592847,776.672717,8676.002550,6158.919933,596.711966,66.301330
893,TCGA-3C-AALK,16301.894223,14298.570862,4169.872416,33188.136433,938.003659,369.978241,19877.625110,11133.080555,3103.464543,218.722431
1123,TCGA-4H-AAAK,63599.110508,36470.689263,4700.813746,27583.891056,133.558817,257.985407,51532.014317,7938.188148,2940.577030,27.396680

In [25]:
filter10.to_csv('D:\\2020\\資料科學\\final-project\\DES\\diffmRNAExp_f_t10.csv',index=False)

In [26]:
filter100=transfer.iloc[:,0:101]
filter100.to_csv('D:\\2020\\資料科學\\final-project\\DES\\diffmRNAExp_f_t100.csv',index=False)
filter1000=transfer.iloc[:,0:1001]
filter1000.to_csv('D:\\2020\\資料科學\\final-project\\DES\\diffmRNAExp_f_t1000.csv',index=False)
filter2000=transfer.iloc[:,0:2001]
filter2000.to_csv('D:\\2020\\資料科學\\final-project\\DES\\diffmRNAExp_f_t2000.csv',index=False)
filter3000=transfer.iloc[:,0:3001]
filter3000.to_csv('D:\\2020\\資料科學\\final-project\\DES\\diffmRNAExp_f_t3000.csv',index=False)

In [27]:
clinical_df=pd.read_csv('D:\\2020\\資料科學\\final-project\\clinical\\clinical_filter2.csv',engine='python')

In [28]:
clinical_df=clinical_df.rename(columns={'case_submitter_id':'id','vital_status':'fstatus'})

In [29]:
clinical_df.head()

,id,ethnicity,gender,race,age_at_index,age_at_diagnosis,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,primary_diagnosis,prior_malignancy,tissue_or_organ_of_origin,treatment_type,fstatus,futime
0,TCGA-E9-A295,not hispanic or latino,female,white,71,25957.0,M0,N0 (i-),Stage IIA,T2,"Lobular carcinoma, NOS",no,"Breast, NOS","Pharmaceutical Therapy, NOS",Alive,375
1,TCGA-AO-A0J9,not hispanic or latino,female,white,61,22642.0,M0,N3,Stage IIIC,T2,"Lobular carcinoma, NOS",no,"Breast, NOS","Radiation Therapy, NOS",Alive,1613
2,TCGA-E2-A1L7,not hispanic or latino,female,white,40,14854.0,M0,N2,Stage IIIA,T2,"Infiltrating duct carcinoma, NOS",no,"Breast, NOS","Radiation Therapy, NOS",Alive,1836
3,TCGA-BH-A0HF,not hispanic or latino,female,white,77,28233.0,M0,N0 (i-),Stage IA,T1c,"Infiltrating duct carcinoma, NOS",no,"Breast, NOS","Radiation Therapy, NOS",Alive,727
4,TCGA-A8-A08H,not hispanic or latino,female,white,66,24137.0,M0,N0,Stage IIA,T2,"Infiltrating duct carcinoma, NOS",no,"Breast, NOS","Pharmaceutical Therapy, NOS",Alive,0

In [30]:
cate=clinical_df.columns[clinical_df.dtypes=="object"].tolist()
cate

['id',
 'ethnicity',
 'gender',
 'race',
 'ajcc_pathologic_m',
 'ajcc_pathologic_n',
 'ajcc_pathologic_stage',
 'ajcc_pathologic_t',
 'primary_diagnosis',
 'prior_malignancy',
 'tissue_or_organ_of_origin',
 'treatment_type',
 'fstatus']

In [31]:
cate.remove('id')
cate.remove('fstatus')

In [32]:
oe = OrdinalEncoder()
clinical_df.loc[:,cate] = oe.fit_transform(clinical_df.loc[:,cate])
clinical_df.head()

,id,ethnicity,gender,race,age_at_index,age_at_diagnosis,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,primary_diagnosis,prior_malignancy,tissue_or_organ_of_origin,treatment_type,fstatus,futime
0,TCGA-E9-A295,1.0,0.0,3.0,71,25957.0,0.0,2.0,4.0,4.0,12.0,0.0,0.0,0.0,Alive,375
1,TCGA-AO-A0J9,1.0,0.0,3.0,61,22642.0,0.0,11.0,9.0,4.0,12.0,0.0,0.0,1.0,Alive,1613
2,TCGA-E2-A1L7,1.0,0.0,3.0,40,14854.0,0.0,9.0,7.0,4.0,6.0,0.0,0.0,1.0,Alive,1836
3,TCGA-BH-A0HF,1.0,0.0,3.0,77,28233.0,0.0,2.0,1.0,3.0,6.0,0.0,0.0,1.0,Alive,727
4,TCGA-A8-A08H,1.0,0.0,3.0,66,24137.0,0.0,0.0,4.0,4.0,6.0,0.0,0.0,0.0,Alive,0

In [33]:
clinical_df['fstatus'] = clinical_df['fstatus'].map({'Alive': 1, 'Dead': 0})
clinical_df.head()

,id,ethnicity,gender,race,age_at_index,age_at_diagnosis,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,primary_diagnosis,prior_malignancy,tissue_or_organ_of_origin,treatment_type,fstatus,futime
0,TCGA-E9-A295,1.0,0.0,3.0,71,25957.0,0.0,2.0,4.0,4.0,12.0,0.0,0.0,0.0,1,375
1,TCGA-AO-A0J9,1.0,0.0,3.0,61,22642.0,0.0,11.0,9.0,4.0,12.0,0.0,0.0,1.0,1,1613
2,TCGA-E2-A1L7,1.0,0.0,3.0,40,14854.0,0.0,9.0,7.0,4.0,6.0,0.0,0.0,1.0,1,1836
3,TCGA-BH-A0HF,1.0,0.0,3.0,77,28233.0,0.0,2.0,1.0,3.0,6.0,0.0,0.0,1.0,1,727
4,TCGA-A8-A08H,1.0,0.0,3.0,66,24137.0,0.0,0.0,4.0,4.0,6.0,0.0,0.0,0.0,1,0

In [34]:
j=clinical_df.shape[0]
for i in range(j):
    if (pd.isnull(clinical_df.ix[i,'age_at_diagnosis'])==True):
        clinical_df.ix[i,'age_at_diagnosis']=clinical_df.ix[i,'age_at_index']*365

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until

In [35]:
# format(float(futime)/365,'.4f')
clinical_df['futime']=clinical_df['futime'].apply(lambda x: x/365)
clinical_df['age_at_diagnosis']=clinical_df['age_at_diagnosis'].apply(lambda x: x/365)
clinical_df.head()

,id,ethnicity,gender,race,age_at_index,age_at_diagnosis,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,primary_diagnosis,prior_malignancy,tissue_or_organ_of_origin,treatment_type,fstatus,futime
0,TCGA-E9-A295,1.0,0.0,3.0,71,71.115068,0.0,2.0,4.0,4.0,12.0,0.0,0.0,0.0,1,1.027397
1,TCGA-AO-A0J9,1.0,0.0,3.0,61,62.032877,0.0,11.0,9.0,4.0,12.0,0.0,0.0,1.0,1,4.419178
2,TCGA-E2-A1L7,1.0,0.0,3.0,40,40.695890,0.0,9.0,7.0,4.0,6.0,0.0,0.0,1.0,1,5.030137
3,TCGA-BH-A0HF,1.0,0.0,3.0,77,77.350685,0.0,2.0,1.0,3.0,6.0,0.0,0.0,1.0,1,1.991781
4,TCGA-A8-A08H,1.0,0.0,3.0,66,66.128767,0.0,0.0,4.0,4.0,6.0,0.0,0.0,0.0,1,0.000000

In [36]:
clinical_df.isnull().sum()

id                           0
ethnicity                    0
gender                       0
race                         0
age_at_index                 0
age_at_diagnosis             0
ajcc_pathologic_m            0
ajcc_pathologic_n            0
ajcc_pathologic_stage        0
ajcc_pathologic_t            0
primary_diagnosis            0
prior_malignancy             0
tissue_or_organ_of_origin    0
treatment_type               0
fstatus                      0
futime                       0
dtype: int64

In [37]:
clinical_df=clinical_df.drop(columns=['age_at_index'])

In [38]:
clinical_df.to_csv('D:\\2020\\資料科學\\final-project\\clinical\\clinical_filter_final.csv',index=False)

In [39]:
clinical_gene10=pd.merge(filter10,clinical_df,how='inner')
clinical_gene10.head()

,id,MMP11,COL10A1,CAV1,GSN,OXTR,CHRDL1,COL11A1,DST,SYNM,...,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,primary_diagnosis,prior_malignancy,tissue_or_organ_of_origin,treatment_type,fstatus,futime
0,TCGA-3C-AAAU,21873.126656,3520.656342,1012.464785,9876.390778,225.286667,236.771869,1597.326642,12505.618701,2793.554669,...,2.0,15.0,11.0,12.0,12.0,0.0,0.0,0.0,1,11.087671
1,TCGA-3C-AALI,18143.286550,7426.918006,2303.185472,22327.786889,3922.256448,380.538689,15369.772361,11665.577409,1878.464389,...,0.0,5.0,5.0,4.0,6.0,0.0,0.0,0.0,1,10.972603
2,TCGA-3C-AALJ,27974.425254,7941.952116,3618.158269,25587.577390,177.592847,776.672717,8676.002550,6158.919933,596.711966,...,0.0,5.0,5.0,4.0,6.0,0.0,0.0,1.0,1,4.038356
3,TCGA-3C-AALK,16301.894223,14298.570862,4169.872416,33188.136433,938.003659,369.978241,19877.625110,11133.080555,3103.464543,...,0.0,1.0,1.0,3.0,6.0,0.0,0.0,0.0,1,3.967123
4,TCGA-4H-AAAK,63599.110508,36470.689263,4700.813746,27583.891056,133.558817,257.985407,51532.014317,7938.188148,2940.577030,...,0.0,10.0,7.0,4.0,12.0,0.0,0.0,0.0,1,0.953425

In [40]:
clinical_gene10.shape

(1091, 25)

In [41]:
clinical_gene10.to_csv('D:\\2020\\資料科學\\final-project\\clinical\\clinical_gene10.csv',index=False)

In [42]:
clinical_gene100=pd.merge(filter100,clinical_df,how='inner')
clinical_gene100.to_csv('D:\\2020\\資料科學\\final-project\\clinical\\clinical_gene100.csv',index=False)
clinical_gene1000=pd.merge(filter1000,clinical_df,how='inner')
clinical_gene1000.to_csv('D:\\2020\\資料科學\\final-project\\clinical\\clinical_gene1000.csv',index=False)
clinical_gene2000=pd.merge(filter2000,clinical_df,how='inner')
clinical_gene2000.to_csv('D:\\2020\\資料科學\\final-project\\clinical\\clinical_gene2000.csv',index=False)
clinical_gene3000=pd.merge(filter3000,clinical_df,how='inner')
clinical_gene3000.to_csv('D:\\2020\\資料科學\\final-project\\clinical\\clinical_gene3000.csv',index=False)